# Colors
set -sa terminal-features ",alacritty:RGB"

# General
set -g status-left-length 40
set -sg escape-time 10
set -g focus-events on

# Better
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none
set -g mouse on

# Indexing
set -g base-index 1
setw -g pane-base-index 1

# Theme
set -g status-right "#[bg=#a9b1d6,fg=#24283b,bold] #S #[bg=default,fg=default,nobold]" 
set -g status-left ""
set -g status-style "bg=#1f2335"
set -g pane-border-status "off"
set -g pane-active-border-style "fg=#9ece6a,bg=default"
set -g pane-border-style "fg=#9ece6a,bg=default"
set -g window-status-current-format "#[bg=#a9b1d6,fg=#24283b,bold] #I - #W #[bg=default,nobold]"
set -g window-status-format "#[bg=#414868] #I - #W #[bg=default]"
set -g window-status-separator '#[bg=#1f2335] #[bg=default]'

# Keymaps
bind r source-file ~/.config/tmux/tmux.conf

bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
